version: "2"

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /usr/share/nginx/html:/usr/share/nginx/html
      - ${PWD}/dhparam.pem:/etc/nginx/ssl/dhparam.pem
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/site.nginx.conf:/etc/nginx/sites-available/blog.sampastoriza.com
    volumes_from:
      - blog-api
    links:
      - blog-api:blog-api
  blog-api:
    image: blog-api
    restart: always
    build: .
    env_file:
      - production.env
    ports:
      - "3000:3000"
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    build:
      context: .
      args:
          WORKING_DIR: /usr
    command: node server-dist/blog.min.js
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongo/data/db
    ports:
      - 27017
    restart: always
  redis:
    container_name: redis
    image: redis
    volumes:
      - ./redis/data
    ports:
      - 6379
    restart: always