version: '2'

services:
  blog-api:
    image: blog-api
    build: .
    environment:
      NODE_ENV: production
      REDIS: redis
      MONGO: mongo
    build:
      context: .
      args:
          WORKING_DIR: /usr/src/app
    command: npm start
    ports:
      - 3000:3000
    restart: always
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /mongo/data/db
    ports:
      - 27017
    restart: always
  redis:
    container_name: redis
    image: redis
    volumes:
      - /redis/data
    ports:
      - 6379
    restart: always
