version: "2"

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /usr/share/nginx/html:/usr/share/nginx/html
      - ${PWD}/dhparam.pem:/etc/nginx/ssl/dhparam.pem
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/site.nginx.conf:/etc/nginx/sites-available/blog.sampastoriza.com
    volumes_from:
      - blog-api
    links:
      - blog-api:blog-api
  blog-api:
    image: blog-api
    restart: always
    build: .
    environment:
      NODE_ENV: production
      REDIS: redis
      MONGO: mongo
      VIRTUAL_HOST: blog.sampastoriza.com
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: blog.sampastoriza.com
      LETSENCRYPT_EMAIL: sampastoriza@yahoo.com
    ports:
      - "3000:3000"
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /mongo/data/db
    ports:
      - 27017
    restart: always
  redis:
    container_name: redis
    image: redis
    volumes:
      - /redis/data
    ports:
      - 6379
    restart: always